#!/bin/bash
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"
BUILD_ROOT="${AUDITOR_BUILD_ROOT:-$PROJECT_DIR/.build}"
mkdir -p "$BUILD_ROOT/module-cache"
export CLANG_MODULE_CACHE_PATH="$BUILD_ROOT/module-cache"
export SWIFTPM_MODULECACHE_OVERRIDE="$BUILD_ROOT/module-cache"
swift build -c release --product AgentMeter --scratch-path "$BUILD_ROOT/spm" --cache-path "$BUILD_ROOT/cache" "$@"
swift build -c release --product AXInspector --scratch-path "$BUILD_ROOT/spm" --cache-path "$BUILD_ROOT/cache" "$@"
swift build -c release --product LogInspector --scratch-path "$BUILD_ROOT/spm" --cache-path "$BUILD_ROOT/cache" "$@"
BIN_DIR="$(swift build -c release --show-bin-path --scratch-path "$BUILD_ROOT/spm")"
APP="$PROJECT_DIR/build/Agent Meter.app"
mkdir -p "$APP/Contents/MacOS"
cp "$BIN_DIR/AgentMeter" "$APP/Contents/MacOS/AgentMeter"
cp Config/Info.plist "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c 'Set :CFBundleExecutable AgentMeter' "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c 'Set :CFBundleIdentifier local.agentmeter.app' "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c 'Set :LSMinimumSystemVersion 13.0' "$APP/Contents/Info.plist"
codesign --force --sign - "$APP"
cp "$BIN_DIR/AXInspector" "$PROJECT_DIR/build/AXInspector"
cp "$BIN_DIR/LogInspector" "$PROJECT_DIR/build/LogInspector"
printf 'Built: %s\n' "$APP"
